Added sql syntaxes
rymizuki/coral-sql pull request #2
Opened 2021-01-22 09:50 UTC by rymizuki

# 課題

- limit, offset, having, group_by のサポートがない
- select文を任意に指定できるようにしたい

2021-01-24 16:45 UTC, bo-ri commented on src/Builder.php
> +            $this->getGroupBy(),
評価順序はGROUP BY => HAVINGだから逆にしたい？
SQLの自体のシンタックスエラーは出ないんですかね

2021-01-25 04:24 UTC, ug23 requested changes
- groupByのクエリを返すところで肝心のカンマ区切りしたカラムを入れ忘れていたのでsuggestionいれました
- php8.0で以下の `PHP_Token_NAME_QUALIFIED` がないというエラーがでています 
  - https://travis-ci.org/github/rymizuki/coral-sql/jobs/755667452#L346

2021-01-25 04:24 UTC, ug23 commented on src/Builder.php
> +            "GROUP BY\n${indent}",
```suggestion
            "GROUP BY\n${indent}%s",
```

2021-01-25 06:56 UTC, rymizuki commented
> php8.0で以下の `PHP_Token_NAME_QUALIFIED` がないというエラーがでています

これはcodeceptionだなぁ....

2021-01-25 09:56 UTC, rymizuki commented on src/Builder.php
> +            $this->getGroupBy(),
cbca7fbde0cc50169b1b346ee5a7026a3bcf227f
こちらで修正しました

2021-01-25 10:00 UTC, bo-ri commented
LGTMです！

2021-01-25 10:01 UTC, bo-ri commented on src/Builder.php
> +            $this->getGroupBy(),
resolved

2021-01-25 11:15 UTC, ug23 approved these changes
LGTMなのでCI通ったらOKです

2021-01-25 12:16 UTC, merged